export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";

export const GET_USER_PROFILE_REQUEST = "GET_USER_PROFILE_REQUEST";
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
export const GET_USER_PROFILE_FAILURE = "GET_USER_PROFILE_FAILURE";

// 👇 Social Auth
export const SOCIAL_AUTH_REQUEST = "SOCIAL_AUTH_REQUEST";
export const SOCIAL_AUTH_SUCCESS = "SOCIAL_AUTH_SUCCESS";
export const SOCIAL_AUTH_FAILURE = "SOCIAL_AUTH_FAILURE";


//update user
export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE";


//FIND USER BY ID

export const FIND_USER_BY_ID_REQUEST = "FIND_USER_BY_ID_REQUEST";
export const FIND_USER_BY_ID_SUCCESS = "FIND_USER_BY_ID_SUCCESS";
export const FIND_USER_BY_ID_FAILURE = "FIND_USER_BY_ID_FAILURE";

//FOLLOW USERS
export const FOLLOW_USER_REQUEST = "UPDATE_USER_REQUEST";
export const FOLLOW_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const FOLLOW_USER_FAILURE = "UPDATE_USER_FAILURE";

export const FETCH_ALL_USERS_REQUEST = "FETCH_ALL_USERS_REQUEST";
export const FETCH_ALL_USERS_SUCCESS = "FETCH_ALL_USERS_SUCCESS";
export const FETCH_ALL_USERS_FAILURE = "FETCH_ALL_USERS_FAILURE"


//logout
export const LOGOUT="LOGOUT";
