export const TWEET_CREATE_REQUEST="TWEET_CREATE_REQUEST";
export const TWEET_CREATE_SUCCESS="TWEET_CREATE_SUCCESS";
export const TWEET_CREATE_FAILURE="TWEET_CREATE_FAILURE";


export const TWEET_EDIT_REQUEST = "TWEET_EDIT_REQUEST";
export const TWEET_EDIT_SUCCESS = "TWEET_EDIT_SUCCESS";
export const TWEET_EDIT_FAILURE = "TWEET_EDIT_FAILURE";

export const TWEET_DELETE_REQUEST = "TWEET_DELETE_REQUEST";
export const TWEET_DELETE_SUCCESS = "TWEET_DELETE_SUCCESS";
export const TWEET_DELETE_FAILURE = "TWEET_DELETE_FAILURE";

export const TWEET_GET_ALL_REQUEST = "TWEET_GET_ALL_REQUEST";
export const TWEET_GET_ALL_SUCCESS = "TWEET_GET_ALL_SUCCESS";
export const TWEET_GET_ALL_FAILURE = "TWEET_GET_ALL_FAILURE";


export const TWEET_GET_USER_REQUEST = "TWEET_GET_USER_REQUEST";
export const TWEET_GET_USER_SUCCESS = "TWEET_GET_USER_SUCCESS";
export const TWEET_GET_USER_FAILURE = "TWEET_GET_USER_FAILURE";


export const USER_LIKE_TWEET_REQUEST = "USER_LIKE_TWEET_REQUEST";
export const USER_LIKE_TWEET_SUCCESS = "USER_LIKE_TWEET_SUCCESS";
export const USER_LIKE_TWEET_FAILURE = "USER_LIKE_TWEET_FAILURE";


export const TWEET_LIKE_REQUEST = "TWEET_LIKE_REQUEST";
export const TWEET_LIKE_SUCCESS = "TWEET_LIKE_SUCCESS";
export const TWEET_LIKE_FAILURE = "TWEET_LIKE_FAILURE";


export const FIND_TWEET_BY_ID_REQUEST = "FIND_TWEET_BY_ID_REQUEST";
export const FIND_TWEET_BY_ID_SUCCESS = "FIND_TWEET_BY_ID_SUCCESS";
export const FIND_TWEET_BY_ID_FAILURE = "FIND_TWEET_BY_ID_FAILURE";


